dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0

before_install:
  - chmod a+x gradlew

script: ./gradlew test

notifications:
  webhooks:
    urls: https://vz8j8wm4oh.execute-api.us-east-1.amazonaws.com/dev/travisBuilds
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
